---
title: "Test Presentation Title"
subtitle: "Test Presentations Subtitle"
author: "Damian Betebenner"
institute: "Center for Assessment"
date: "June 22nd, 2022 (updated: `r toOrdinal::toOrdinalDate(Sys.Date())`)"
output:
  cfaDocs::cfaXaringan:
    cfa_theme: 'cfa-b'
    include: !expr list(
      xaringanExtra = 'default',
      xExtra_use = c('share_again', 'tile_view', 'clipboard'))


---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r style-share-again, echo=FALSE}
xaringanExtra::style_share_again(
  share_buttons = c("twitter"),
  background = "#009C49",
  foreground = "#FFFFFF"
)
```

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "https://centerforassessment.github.io/assets/favicon.png",
  width = "55px",
  height = "64px",
  position = xaringanExtra::css_position(top = "0.5em", right = "0.5em"),
  link_url = "https://www.nciea.org"
)
```

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
```

```{r xaringanExtra-clipboard, echo=FALSE}
xaringanExtra::use_clipboard()
```

---
class: inverse, center, middle

# Section Header

---
class: highlight-last-item

# Some Bullets

--

- Bullet 1

--

- Bullet 2

--

- Bullet 3